<?php

namespace RennesJeux\SondageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
	public function sessionsProposees($limit)
    {
    	$qb =  $this->createQueryBuilder('s')
    		->innerJoin('s.jeu', 'jeu')
    		->addSelect('jeu')
    		->where('s.date >= :datedujour')
    			->setParameter('datedujour', new \Datetime(date('Ymd')))
    		->andWhere('s.nbParticipants < jeu.nbparticipantmin')
            ->orderBy('s.date', 'ASC');

         if ($limit)
         {
         	$qb->setMaxResults(5);
         }

        return $qb;
    }

    public function sessionsValidees($limit)
    {
    	$qb = $this->createQueryBuilder('s')
    		->innerJoin('s.jeu', 'jeu')
    		->addSelect('jeu')
    		->where('s.nbParticipants >= jeu.nbparticipantmin')
    		->andWhere('s.date >= :datedujour')
    			->setParameter('datedujour', new \Datetime(date('Ymd')))
    		->orderBy('s.date', 'ASC');

    	if ($limit)
		{
			$qb->setMaxResults(5);
		}

        return $qb;
    }

    public function Execution($qb)
    {
    	return $qb->getQuery()
           ->getArrayResult();
    }

    public function requetePaginee($qb)
    {
    	/*$adapter = new DoctrineORMAdapter($qb,false,true);
        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setMaxPerPage(5);
        $pagerfanta->setCurrentPage($page);

        return $pagerfanta;*/
    }
}
