rennes_jeux_sondage_homepage:
    path:     /
    defaults: { _controller: RennesJeuxSondageBundle:Default:index }
    
rennes_jeux_sondage_liste:
    path:    /liste/{affichage}
    defaults: 
      _controller: RennesJeuxSondageBundle:Session:liste 
      affichage: apercu
    requirements:
      affichage: apercu|proposees|validees
    
rennes_jeux_sondage_login:
    path:    /login
    defaults: { _controller: RennesJeuxSondageBundle:User:login }

rennes_jeux_sondage_disconnect:
    path:    /disconnect
    defaults: { _controller: RennesJeuxSondageBundle:User:disconnect }

rennes_jeux_sondage_proposees:
    path:    /proposees/{apercu}
    defaults: 
      _controller: RennesJeuxSondageBundle:Session:proposees
      apercu: false
    requirements:
      apercu: true|false

rennes_jeux_sondage_validees:
    path:    /validees/{apercu}
    defaults: 
      _controller: RennesJeuxSondageBundle:Session:validees
      apercu: false
    requirements:
      apercu: true|false

rennes_jeux_sondage_inscription:
    path:    /inscription/{id}
    defaults: { _controller: RennesJeuxSondageBundle:User:inscription }
    requirements:
        id: \d+

rennes_jeux_sondage_desinscription:
    path:    /desinscription/{id}
    defaults: { _controller: RennesJeuxSondageBundle:User:desinscription }
    requirements:
        id: \d+

rennes_jeux_sondage_add:
    path:    /ajout
    defaults: { _controller: RennesJeuxSondageBundle:Jeux:add }