# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    RennesJeux\UserBundle\Entity\User: plaintext
    FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
        entity:
            class:      RennesJeux\UserBundle\Entity\User
            property:   username
    fos_userbundle:
        id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:      ^/
      anonymous:    true
      provider:     fos_userbundle
      form_login:
        login_path:  fos_user_security_login
        check_path:  fos_user_security_check
        use_forward: false
        always_use_default_target_path: true
        default_target_path:            /sondage
        use_referer:                    false        
      logout:
        path:       fos_user_security_logout
        target:     /login

  access_control:
    - { path: ^/sondage, roles: IS_AUTHENTICATED_REMEMBERED }
